// Live market-data feed for Finance_AI_Dashboard.html
// Regenerated by refresh_market_data.py — do not edit by hand.
window.MARKET_LIVE = {
  "asof": "July 17, 2026 market close (initial snapshot)",
  "updated": "2026-07-20",
  "rates": {"ff": 0.0375, "sofr": 0.0364, "t3m": 0.0384, "t2y": 0.0418, "t10y": 0.0455, "t30y": 0.0506},
  "quotes": {
    "PLTR": {"price": 132.38, "mcap": 317400, "ev": 309500, "fpe": 83.3, "evrev": 59.3},
    "HUBS": {"price": 224.26, "mcap": 11490, "ev": 10040, "fpe": 16.4, "evrev": 3.0},
    "SOFI": {"price": 17.28, "mcap": 22170, "ev": 20520, "fpe": 26.4, "evrev": 5.2}
  }
};
